databases:
  - name: auto-withdraw-db
    databaseName: auto_withdraw_db
    user: postgres
    plan: free

services:
  - type: web
    name: auto-withdraw-backend
    env: node
    plan: free
    # Root directory for monorepo deployment
    rootDir: auto-withdraw-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auto-withdraw-db
          property: connectionString
      - key: MAXPAY_API_KEY
        value: pkTest_fwaiBzXH9N89XPis4rW4P7kaQe7Og5TX
        generateValue: false
      - key: MAXPAY_API_SECRET
        value: skTest_XiZbsgabZgn8kPChtTnlTj3xB66r2h78
        generateValue: false
      - key: MAXPAY_MERCHANT_ID
        value: ID12345
        generateValue: false
      - key: MAXPAY_BASE_URL
        value: https://api.maxpay.com
        generateValue: false
      - key: FRONTEND_URL
        value: https://payment-admin-dashboard-epidmfp5f-maximus-projects-d45483e6.vercel.app
        generateValue: false
      - key: NODE_ENV
        value: production
        generateValue: false
      - key: PORT
        value: 10000
        generateValue: false
